function connprep_main( ...
	num_initial_vols_to_drop, ...
	num_vols_to_analyze, ...
	bandpasslo_hz, ...
	bandpasshi_hz, ...
	mot_PCs, ...
	motderiv_PCs, ...
	wmcsf_PCs, ...
	slorder, ...
	fmri_niigz, ...
	mt1_niigz, ...
	deffwd_niigz, ...
	gray_niigz, ...
	white_niigz, ...
	csf_niigz, ...
	project, ...
	subject, ...
	session, ...
	scan, ...
	magick_path, ...
	out_dir ...
	)

%% SPM init
spm_jobman('initcfg')


%% Identify the MNI space geometry we will use for output images
mnigeom_nii = [spm('dir') '/canonical/avg152T1.nii'];


%% Copy files to working directory with consistent names and unzip
disp('File prep')
[fmri_nii,mt1_nii,deffwd_nii,gray_nii,white_nii,csf_nii] = prep_files( ...
	out_dir,fmri_niigz,mt1_niigz,deffwd_niigz,gray_niigz,white_niigz,csf_niigz);


%% Drop unwanted volumes
fprintf('Drop volumes from %s\n',fmri_nii);
dfmri_nii = drop_volumes(fmri_nii,num_initial_vols_to_drop,num_vols_to_analyze);


%% Find the TR
tr = get_tr(fmri_nii);


%% Slice timing correction
% Slice timing correction interpolates across time, possibly polluting high
% quality vols with artifact signal from nearby vols with high FD/DVARS
fprintf('Slice timing correction "%s" on %s\n',slorder,dfmri_nii);
adfmri_nii = slice_timing_correction(dfmri_nii,tr,slorder);


%% Realignment
fprintf('Realignment of %s\n',adfmri_nii);
[radfmri_nii,meanradfmri_nii,rp_txt] = realignment(adfmri_nii);


%% Make masked anat for coreg in T1 native space
[mmt1_nii,mask_nii] = mask_anat(mt1_nii,gray_nii,white_nii,csf_nii);


%% Coregister fmri to anat
fprintf('Coregister:\n    %s\n    %s\n',meanradfmri_nii,mmt1_nii)
[cradfmri_nii,cmeanradfmri_nii] = coregister( ...
	radfmri_nii,meanradfmri_nii,mmt1_nii);


%% Reslice images to native space post-realignment
ncradfmri_nii = reslice(cradfmri_nii,cmeanradfmri_nii);


%% Compute FD, DVARS
disp('Volume quality')
[FD,DVARS] = volume_quality(out_dir,cmeanradfmri_nii,ncradfmri_nii,rp_txt);


%% Warp fMRI to MNI space
% Start with the registered, but un-resliced, images to minimize
% interpolation steps
fprintf('Warping:\n    %s\n    %s\n',cmeanradfmri_nii,cradfmri_nii);
wcmeanradfmri_nii = warp_images(deffwd_nii,cmeanradfmri_nii, ...
	mnigeom_nii,1,out_dir);
wcradfmri_nii = warp_images(deffwd_nii,cradfmri_nii, ...
	mnigeom_nii,1,out_dir);


%% Check registration
% First warp GM to high resolution space to get better edges
wgrayedge_nii = warp_images(deffwd_nii,gray_nii, ...
	[spm('dir') '/tpm/TPM.nii'],1,out_dir);
wedge_nii = coreg_check(out_dir,wcmeanradfmri_nii,wgrayedge_nii,0.5);


%% Process fMRI: filter, warp

disp('Filter')

% First warp gray matter to MNI for masking
wgray_nii = warp_images(deffwd_nii,gray_nii,mnigeom_nii,1,out_dir);

% Remove gray matter signal, no scrub
[filtered_removegm_nii,confounds_removegm_txt] = connectivity_filter( ...
	out_dir, ncradfmri_nii, rp_txt, gray_nii, white_nii, csf_nii, tr, ...
	slorder, num_initial_vols_to_drop, ...
	bandpasslo_hz, bandpasshi_hz, FD, DVARS, [], ...
	mot_PCs, motderiv_PCs, wmcsf_PCs, ...
	1, project, subject, session, [scan ' Native'] ...
	);
wfiltered_removegm_nii = connectivity_filter_apply( ...
	out_dir,wcradfmri_nii,wgray_nii,confounds_removegm_txt,'removegm_noscrub');


% Keep gray matter signal, no scrub
[filtered_keepgm_nii,confounds_keepgm_txt] = connectivity_filter( ...
	out_dir, ncradfmri_nii, rp_txt, gray_nii, white_nii, csf_nii, tr, ...
	slorder, num_initial_vols_to_drop, ...
	bandpasslo_hz, bandpasshi_hz, FD, DVARS, [], ...
	mot_PCs, motderiv_PCs, wmcsf_PCs, ...
	0, project, subject, session, [scan ' Native'] ...
	);
wfiltered_keepgm_nii = connectivity_filter_apply( ...
	out_dir,wcradfmri_nii,wgray_nii,confounds_keepgm_txt,'keepgm_noscrub');



%% Make output PDF
% First warp mask to MNI for QA images
wmask_nii = warp_images(deffwd_nii,mask_nii,mnigeom_nii,0,out_dir);

make_network_maps( ...
	out_dir, ...
	wfiltered_removegm_nii, ...
	wcmeanradfmri_nii, ...
	wmask_nii, ...
	wedge_nii, ...
	project, ...
	subject, ...
	session, ...
	scan ...
	)

make_pdf(out_dir,magick_path);


%% Mask MNI space images to save space
mask_mni({wfiltered_removegm_nii,wfiltered_keepgm_nii});


%% Zip output images
zip_outputs(out_dir);


%% Exit
if isdeployed
	exit
end

