function make_pdf(out_dir)

system( [ ...
	'cd ' out_dir ' && ' ...
	'convert ' ...
	'connectivity_removegm_noscrub.png ' ...
	'connectivity_keepgm_noscrub.png ' ...
	'coreg_check.png ' ...
	'connmap_FrontoParietal.png ' ...
	'connmap_DefaultMode.png ' ...
	'connmap_DorsalAttention.png ' ...
	'connmap_VentralAttention.png ' ...
	'connmap_Somatomotor.png ' ...
	'connmap_Visual.png ' ...
	'connmap_Limbic.png ' ...
	'connprep.pdf' ...
	] );
