function make_pdf(out_dir)

magick_path = '/usr/local/bin';

system( [ ...
	'cd ' out_dir ' && ' ...
	magick_path '/convert ' ...
	'connectivity_removegm_noscrub.png ' ...
	'connectivity_keepgm_noscrub.png ' ...
	'coreg_check.png ' ...
	'connprep.pdf' ...
	] );
