function ncradfmri_nii = reslice(cradfmri_nii,cmeanradfmri_nii)

flags = struct( ...
	'mask',true, ...
	'mean',false, ...
	'interp',1, ...
	'which',1, ...
	'wrap',[0 0 0], ...
	'prefix','n' ...
	);

spm_reslice({cmeanradfmri_nii;cradfmri_nii},flags);

[p,n,e] = fileparts(cradfmri_nii);
ncradfmri_nii = fullfile(p,['n' n e]);

